name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:[14.x,16.x,18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies (client)
      run: |
        cd frontend
        npm install

    - name: Install dependencies (server)
      run: |
        cd Backend
        npm install

    - name: Build client
      run: |
        cd frontend
        npm run build